import Image1 from "../assets/products/Aroma.png";

export const FRESHENERS = [
  {
    id: "1",
    image: Image1,
    category: "Ароматизатор для автомобиля",
    title: "NIKI Камуфляж Citrus & Musk",
    subtitle: "Цитрус и мускус",
    price: 1777,
    aroma1: "цветочный",
    aroma2: "цитрусовый",
    aroma3: "",
    aroma4: "",
    aroma5: "",
    top_note1: "бергамот",
    top_note2: "лимон",
    top_note3: "ревень",
    top_note4: "флердоранж",
    top_note5: "",
    middle_note1: "свежий имбирь",
    middle_note2: "жасмин",
    middle_note3: "герань",
    middle_note4: "зелень",
    middle_note5: "",
    base_note1: "ирис",
    base_note2: "ветивер",
    base_note3: "кедровая древесина",
    base_note4: "амбра",
    base_note5: "",
    description:
      "Это он, легендарный NIKI! Не просто ароматизатор для авто, а стильный и модный аксессуар. Его милый внешний вид — заслуга мастера итальянского стиля Лука Трацци, а влюбляющие в себя ароматы — дело рук и носов парфюмеров знаменитого французского концерна MANE.",
  },
  {
    id: "2",
    image: Image1,
    category: "Ароматизатор для автомобиля",
    title: "NIKI Камуфляж Citrus & Musk",
    subtitle: "Цитрус и мускус",
    price: 2777,
    aroma1: "цветочный",
    aroma2: "цитрусовый",
    aroma3: "",
    aroma4: "",
    aroma5: "",
    top_note1: "бергамот",
    top_note2: "лимон",
    top_note3: "ревень",
    top_note4: "флердоранж",
    top_note5: "",
    middle_note1: "свежий имбирь",
    middle_note2: "жасмин",
    middle_note3: "герань",
    middle_note4: "зелень",
    middle_note5: "",
    base_note1: "ирис",
    base_note2: "ветивер",
    base_note3: "кедр",
    base_note4: "амбра",
    base_note5: "",
    description:
      "Это он, легендарный NIKI! Не просто ароматизатор для авто, а стильный и модный аксессуар. Его милый внешний вид — заслуга мастера итальянского стиля Лука Трацци, а влюбляющие в себя ароматы — дело рук и носов парфюмеров знаменитого французского концерна MANE.",
  },
  {
    id: "3",
    image: Image1,
    category: "Ароматизатор для автомобиля",
    title: "NIKI Камуфляж Citrus & Musk",
    subtitle: "Цитрус и мускус",
    price: 3777,
    aroma1: "цветочный",
    aroma2: "цитрусовый",
    aroma3: "",
    aroma4: "",
    aroma5: "",
    top_note1: "бергамот",
    top_note2: "лимон",
    top_note3: "ревень",
    top_note4: "флердоранж",
    top_note5: "",
    middle_note1: "свежий имбирь",
    middle_note2: "жасмин",
    middle_note3: "герань",
    middle_note4: "зелень",
    middle_note5: "",
    base_note1: "ирис",
    base_note2: "ветивер",
    base_note3: "кедровая древесина",
    base_note4: "амбра",
    base_note5: "",
    description:
      "Это он, легендарный NIKI! Не просто ароматизатор для авто, а стильный и модный аксессуар. Его милый внешний вид — заслуга мастера итальянского стиля Лука Трацци, а влюбляющие в себя ароматы — дело рук и носов парфюмеров знаменитого французского концерна MANE.",
  },
  {
    id: "4",
    image: Image1,
    category: "Ароматизатор для автомобиля",
    title: "NIKI Камуфляж Citrus & Musk",
    subtitle: "Цитрус и мускус",
    price: 4777,
    aroma1: "цветочный",
    aroma2: "цитрусовый",
    aroma3: "",
    aroma4: "",
    aroma5: "",
    top_note1: "бергамот",
    top_note2: "лимон",
    top_note3: "ревень",
    top_note4: "флердоранж",
    top_note5: "",
    middle_note1: "свежий имбирь",
    middle_note2: "жасмин",
    middle_note3: "герань",
    middle_note4: "зелень",
    middle_note5: "",
    base_note1: "ирис",
    base_note2: "ветивер",
    base_note3: "кедровая древесина",
    base_note4: "амбра",
    base_note5: "",
    description:
      "Это он, легендарный NIKI! Не просто ароматизатор для авто, а стильный и модный аксессуар. Его милый внешний вид — заслуга мастера итальянского стиля Лука Трацци, а влюбляющие в себя ароматы — дело рук и носов парфюмеров знаменитого французского концерна MANE.",
  },
];
