import Image1 from "../assets/products/Baccarat.svg";

export const PERFUMES = [
  {
    id: "1",
    image: Image1,
    name: "Baccarat Rouge 540",
    brand: "Maison Francis Kurkjian",
    price3: 333,
    price5: 555,
    price10: 1000,
    price20: 2000,
    price30: 3000,
    perfumer: "Maison Francis Kurkjian & Baccarat",
    country: "France",
    year: 2020,
    sex: "Унисекс",
    compound1: "Можжевельник",
    compound2: "Морские водоросли",
    compound3: "Перец",
    compound4: "",
    compound5: "",
    family1: "Древесный",
    family2: "Пряный",
    family3: "",
    family4: "",
    family5: "",
    note1: "Можжевельник",
    note2: "Перец",
    note3: "Водоросли",
    note4: "",
    note5: "",
    chord1: "Свежий пряный",
    chord2: "Фужерный",
    chord3: "Древесный",
    chord4: "Тёплый пряный",
    chord5: "",
    description:
      "Парфюмерная вода Baccarat Rouge 540 родилась благодаря сотрудничеству между Maison Francis Kurkdjian и Baccarat в честь празднования 250-й годовщины производителя хрусталя.",
    feedback: "Fragrantica.ru",
  },
  {
    id: "2",
    image: Image1,
    name: "Baccarat Rouge 540 Baccarat Rouge 540",
    brand: "Maison Francis Kurkjian Maison Francis Kurkjian",
    price3: 333,
    price5: 555,
    price10: 1000,
    price20: 2000,
    price30: 3000,
    perfumer: "Maison Francis Kurkjian & Baccarat",
    country: "France",
    year: 2020,
    sex: "Унисекс",
    compound1: "Можжевельник",
    compound2: "Морские водоросли",
    compound3: "Перец",
    compound4: "",
    compound5: "",
    family1: "Древесный",
    family2: "Пряный",
    family3: "",
    family4: "",
    family5: "",
    note1: "Можжевельник",
    note2: "Перец",
    note3: "Водоросли",
    note4: "",
    note5: "",
    chord1: "Свежий пряный",
    chord2: "Фужерный",
    chord3: "Древесный",
    chord4: "Тёплый пряный",
    chord5: "",
    description:
      "Парфюмерная вода Baccarat Rouge 540 родилась благодаря сотрудничеству между Maison Francis Kurkdjian и Baccarat в честь празднования 250-й годовщины производителя хрусталя.",
    feedback: "Fragrantica.ru",
  },
  {
    id: "3",
    image: Image1,
    name: "Kilian Apple Brandy on the rocks",
    brand: "",
    price3: 333,
    price5: 555,
    price10: 1000,
    price20: 2000,
    price30: 3000,
    perfumer: "Maison Francis Kurkjian & Baccarat",
    country: "France",
    year: 2020,
    sex: "Унисекс",
    compound1: "Можжевельник",
    compound2: "Морские водоросли",
    compound3: "Перец",
    compound4: "",
    compound5: "",
    family1: "Древесный",
    family2: "Пряный",
    family3: "",
    family4: "",
    family5: "",
    note1: "Можжевельник",
    note2: "Перец",
    note3: "Водоросли",
    note4: "",
    note5: "",
    chord1: "Свежий пряный",
    chord2: "Фужерный",
    chord3: "Древесный",
    chord4: "Тёплый пряный",
    chord5: "",
    description:
      "Парфюмерная вода Baccarat Rouge 540 родилась благодаря сотрудничеству между Maison Francis Kurkdjian и Baccarat в честь празднования 250-й годовщины производителя хрусталя.",
    feedback: "Fragrantica.ru",
  },
  {
    id: "4",
    image: Image1,
    name: "Baccarat Rouge 540",
    brand: "Maison Francis Kurkjian",
    price3: 333,
    price5: 555,
    price10: 1000,
    price20: 2000,
    price30: 3000,
    perfumer: "Maison Francis Kurkjian & Baccarat",
    country: "France",
    year: 2020,
    sex: "Унисекс",
    compound1: "Можжевельник",
    compound2: "Морские водоросли",
    compound3: "Перец",
    compound4: "",
    compound5: "",
    family1: "Древесный",
    family2: "Пряный",
    family3: "",
    family4: "",
    family5: "",
    note1: "Можжевельник",
    note2: "Перец",
    note3: "Водоросли",
    note4: "",
    note5: "",
    chord1: "Свежий пряный",
    chord2: "Фужерный",
    chord3: "Древесный",
    chord4: "Тёплый пряный",
    chord5: "",
    description:
      "Парфюмерная вода Baccarat Rouge 540 родилась благодаря сотрудничеству между Maison Francis Kurkdjian и Baccarat в честь празднования 250-й годовщины производителя хрусталя.",
    feedback: "Fragrantica.ru",
  },
];
