# Generated by Django 5.1.6 on 2025-03-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='sex',
            field=models.CharField(choices=[('M', 'для мужчин'), ('F', 'для женщин'), ('U', 'унисекс')], default='U', max_length=2, verbose_name='Пол'),
        ),
        migrations.DeleteModel(
            name='PerfumeCopy',
        ),
    ]
