# Generated by Django 5.1.6 on 2025-03-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['id'], 'verbose_name': 'Способы доставки', 'verbose_name_plural': 'Способы доставки'},
        ),
        migrations.AddField(
            model_name='gift',
            name='is_actual',
            field=models.BooleanField(choices=[(False, 'Неактуально'), (True, 'Актуально')], default=1, verbose_name='Актуальность'),
        ),
        migrations.AlterField(
            model_name='consumables',
            name='image',
            field=models.ImageField(upload_to='image_consumables', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='consumables',
            name='is_available',
            field=models.BooleanField(choices=[(False, 'Нет в наличии'), (True, 'В наличии')], default=1, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='freshener',
            name='image',
            field=models.ImageField(upload_to='image_fresheners', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='freshener',
            name='is_available',
            field=models.BooleanField(choices=[(False, 'Нет в наличии'), (True, 'В наличии')], default=1, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='image',
            field=models.ImageField(upload_to='image_perfumes', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='is_available',
            field=models.BooleanField(choices=[(False, 'нет в наличии'), (True, 'в наличии')], default=1, verbose_name='Наличие'),
        ),
    ]
