# Generated by Django 5.1.6 on 2025-03-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_delivery_options_gift_is_actual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='is_actual',
        ),
    ]
