# Generated by Django 5.1.6 on 2025-03-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_remove_gift_is_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aroma',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='basenote',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='chord',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='consumables',
            name='image',
            field=models.ImageField(upload_to='image_consumables/%Y/%m/%d/', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='freshener',
            name='image',
            field=models.ImageField(upload_to='image_fresheners/%Y/%m/%d/', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='herodata',
            name='image',
            field=models.ImageField(upload_to='image_heroData/%Y/%m/', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='middlenote',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='image',
            field=models.ImageField(upload_to='image_perfumes/%Y/%m/%d/', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='topnote',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
