# Generated by Django 5.1.6 on 2025-03-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_alter_aroma_name_alter_basenote_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='is_available',
            field=models.BooleanField(choices=[(True, 'в наличии'), (False, 'нет в наличии')], default=1, verbose_name='Наличие'),
        ),
    ]
