# Generated by Django 5.1.6 on 2025-05-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_alter_consumables_aroma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='note1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='note1', to='backend_api.note', verbose_name='Основная нота-1'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='note2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='note2', to='backend_api.note', verbose_name='Основная нота-2'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='note3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='note3', to='backend_api.note', verbose_name='Основная нота-3'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='note4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='note4', to='backend_api.note', verbose_name='Основная нота-4'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='note5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='note5', to='backend_api.note', verbose_name='Основная нота-5'),
        ),
    ]
