# Generated by Django 5.1.6 on 2025-03-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Клиента', 'verbose_name_plural': 'Клиенты и Персонал'},
        ),
    ]
